### ISSUE TITLE
Missing global masternode list in new wallet

### ISSUE THREAD

**Issue by TheSquiffy** [Galilel-Project/galilel#3]
Hi, the list of all masternodes in the network have been removed in the  new wallet, leading to the debug command: **masternode list**

a **masternode list count** would be useful to just get the node count without having to parse a big json.

**Comment by mbroemme** [comment]
![image](https://user-images.githubusercontent.com/936659/49973934-61915a00-ff37-11e8-822a-467f7910a30f.png)

@TheSquiffy Is it enough in Tools -> Information? As it is available there already.
